/**
 * @author wrightwj
 */
package project1;

import java.util.Scanner;

// TODO: Auto-generated Javadoc
/**
 * The Class Board.
 */
public class Board {

	/** The sequence generated by the game */
	private Sequence gameSeq;

	/** The amount of turns allowed */
	private final int TURNS = 7;

	/** The array of strings to print */
	private String[] board = new String[8];

	/** The current turn. */
	private int currTurn;

	/** holds whether the game is done or not. */
	private boolean finished;

	/**
	 * Instantiates a new board.
	 *
	 * @throws Exception if sequence is invalid
	 */
	public Board() throws Exception {
		gameSeq = new Sequence("RGBO");
		currTurn = 0;
		finished = false;
		start();
	}



	/**
	 * starts the game
	 *
	 * @throws Exception if sequence does not have proper string
	 */
	public void start() throws Exception {
		Scanner sc = new Scanner(System.in);
		while (!finished && currTurn <= TURNS) {
			Sequence playerSeq = new Sequence(sc.nextLine());
			board[TURNS-(currTurn)] = gameSeq.compareSequence(playerSeq);
			if (board[TURNS-currTurn].equals("BBBB")) {
				System.out.println(toString());
				System.out.println("You won!");
				finished = true;
			}
			currTurn++;
			if (currTurn >TURNS){
				System.out.println(toString());
				System.out.println("You lose, nerd");
			}
			System.out.println(toString());
		}	
		sc.close();
	}



	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 * prints board with proper symbols
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		for (int i = 0;i<=TURNS;i++) {
			if (board[i] == null) {
				sb.append("____" + "\n");
			} else sb.append(board[i] + "\n");
		}
		return sb.toString();
	}
}
